---
apiVersion: v1
kind: Service
metadata:
  namespace: react
  name: service
spec:
  selector:
    app: react-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: react-app
  name: react-app
  namespace: react
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: react-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: europe-west1-docker.pkg.dev/interview-prj1/web/react-app:latest
          ports:
            - containerPort: 3000
