//FIXUP DOCKER BUILD STAGE AS ITS NOT READING THE DOCKERFILE


def registry = 'europe-west1-docker.pkg.dev/interview-prj1/web'

pipeline {
  agent any
  stages {
    stage('Build image') {
      steps{
        script {
          '''
            which docker
            pwd
            ls -ltra
           docker build  --tag ${image_name} ${build_args}  -f ./Dockerfile .
          '''
        }
      }
    }
    // stage('Test image'){
    //   steps{
    //     script {
    //     docker.withRegistry("${registry}") {
    //     docker.image('react-app').inside {
    //         sh 'make test'
    //         }
    //       }
    //     }
    //   }
    // }
    stage('Pushing Image') {
      steps{
        script {
            '''
            docker image push ("${registry}")
            '''
          }
        }
      }
    }
    stage('Deploying React.js container to Kubernetes') {
      steps {
        script {
          kubernetesDeploy(configs: "deployment.yaml")
        }
      }
    }
  }
}
