//FIXUP DOCKER BUILD STAGE AS ITS NOT READING THE DOCKERFILE


def registry = 'europe-west1-docker.pkg.dev/interview-prj1/web'

pipeline {
  agent any
  stages {
    stage ('check '){
      steps{
        script {
          sh '''
            which docker
            pwd
            ls -ltra
          '''
        }
      }
    }
    stage('Build image') {
      steps{
        script {
         sh '''
           docker build  --tag 'react-app' -f ./react-app/Dockerfile .
          '''
        }
      }
    }
    stage('Test image'){
      steps{
        script {
          sh '''
          docker run -e CI=true react-app npm run --rm test
          '''
        }
      }
    }
    stage('Pushing Image') {
      steps{
        script {
          withCredentials([file(credentialsId: 'my-creds', variable: 'interview-prj1-4e6bb07fceea.json')]) {
           sh  '''
            docker tag react-app europe-west1-docker.pkg.dev/interview-prj1/web/react-app
            docker image push europe-west1-docker.pkg.dev/interview-prj1/web/react-app
            '''
          }
        }
      }
    }
    stage('Deploying React.js container to Kubernetes') {
      steps {
        script {
          kubernetesDeploy(configs: "deployment.yaml")
        }
      }
    }
  }
}

